"use client";
import { useMemo, useState } from "react";
import { completeTask, createTask } from "@/actions/customer-actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Task = { id: string; taskType: "DeliverCylinder" | "CollectEmptyCylinder"; dueDate: Date; status: "Pending" | "Completed"; priority: string; reminderNotes: string | null; customer: { id: string; fullName: string; area: string; phoneNumber: string } };
type Customer = { id: string; fullName: string; area: string };

export function TaskClient({ tasks, customers }: { tasks: Task[]; customers: Customer[] }) {
  const [filter, setFilter] = useState("Pending"); const [query, setQuery] = useState(""); const [message, setMessage] = useState("");
  const filtered = useMemo(() => tasks.filter((t) => (filter === "All" || t.status === filter) && `${t.customer.fullName} ${t.customer.area} ${t.reminderNotes ?? ""}`.toLowerCase().includes(query.toLowerCase())), [tasks, filter, query]);
  async function onCreate(form: FormData) { const res = await createTask(null, form); setMessage(res.message); }
  return <main className="space-y-4 px-4"><form action={onCreate} className="touch-card space-y-3"><h2 className="font-semibold">Create delivery / collection reminder</h2><select name="customerId" className="h-12 w-full rounded-2xl border bg-background px-4">{customers.map((c) => <option key={c.id} value={c.id}>{c.fullName} • {c.area}</option>)}</select><select name="taskType" className="h-12 w-full rounded-2xl border bg-background px-4"><option value="DeliverCylinder">Deliver Cylinder</option><option value="CollectEmptyCylinder">Collect Empty Cylinder</option></select><Input name="dueDate" type="datetime-local" required /><select name="priority" className="h-12 w-full rounded-2xl border bg-background px-4"><option>Medium</option><option>High</option><option>Urgent</option><option>Low</option></select><Textarea name="reminderNotes" placeholder="Reminder notes" /><Button className="w-full">Save reminder</Button></form>{message && <p className="rounded-2xl bg-primary/10 p-3 text-sm font-semibold text-primary">{message}</p>}<div className="sticky top-[88px] z-30 space-y-2 rounded-3xl border bg-card p-3"><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search area/customer" /><div className="grid grid-cols-3 gap-2">{["Pending", "Completed", "All"].map((f) => <Button key={f} type="button" variant={filter === f ? "default" : "secondary"} onClick={() => setFilter(f)}>{f}</Button>)}</div></div><section className="space-y-3">{filtered.map((task) => { const overdue = task.status === "Pending" && new Date(task.dueDate) < new Date(); return <article key={task.id} className="touch-card"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{task.customer.fullName}</h3><p className="text-sm text-muted-foreground">{task.taskType === "DeliverCylinder" ? "Deliver Cylinder" : "Collect Empty Cylinder"} • {task.customer.area}</p><p className="text-sm">Due {new Date(task.dueDate).toLocaleString()}</p>{task.reminderNotes && <p className="mt-2 text-sm">{task.reminderNotes}</p>}</div><Badge className={overdue ? "bg-destructive text-white" : task.status === "Completed" ? "bg-primary text-white" : "bg-amber-500 text-white"}>{overdue ? "Overdue" : task.status}</Badge></div>{task.status === "Pending" && <Button className="mt-3 w-full" onClick={() => completeTask(task.id)}>Mark completed</Button>}</article>; })}</section>{filtered.length === 0 && <div className="touch-card text-center text-muted-foreground">No tasks found.</div>}</main>;
}
